# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: "NPM Install"
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'projects/simplified-ui'
    customCommand: 'version patch'

- script: git commit -am "Updated patch version"

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build-simplified-ui'

- task: Npm@1
  inputs:
    command: 'publish'
    workingDir: 'dist/simplified-ui'